### ISSUE TITLE
Feature Request: Toggle transparency

### ISSUE THREAD

**Issue by hwamil** [MrSloth-dev/Switcheroo.nvim#1]
Hi, thank you for this plugin!

I get bored with themes easily and this totally makes it super convenient to scratch that itch :D

Not sure how to turn on transparency for the themes, so wondering it this can be added as a feature?

Thanks again, ans I hope you will consider this!

**Comment by MrSloth-dev** [comment]
Hello there, at the first thought  I think it's not possible because it needs to customize each plugin individually and each plugin can have different named parameter for transparency. But let me check and I'll get back to you :)

**Comment by MrSloth-dev** [comment]
Hey, for the time being I'm not able to implement the feature that you requested because the transparency parameter name. Maybe in the future I'll find a way to implement

**Comment by hwamil** [comment]
Yeah, didn't think it would be easy since different authors have different variable names for it lol. Thanks for considering it at all. I still think this is an amazing plugin. I've been using themery which is not bad but it is a bit cumbersome to use with having to manually inputting configurations through strings.
